
@host = http://localhost:3000/api
@apiClientes = {{host}}/clientes
@apiProductos = {{host}}/productos




######################
#     clientes       #
######################
GET {{apiClientes}}

###
GET {{apiClientes}}/1

###
POST {{apiClientes}}
Content-Type: application/json

{
"nombre": "Alejandro Martinez",
"direccion": "Carrer de lopez vega, 105"
}

###
PUT {{apiClientes}}/2
Content-Type: application/json

{
"nombre": "Maira Fernandez",
"direccion": "Carrer san genil, 105"
}

###
DELETE {{apiClientes}}/2



######################
#     productos       #
######################
GET {{apiProductos}}

###
GET {{apiProductos}}/1

###
POST {{apiProductos}}
Content-Type: application/json

{
    "id":2,
    "nombre": "Destornillador Phillips",
    "descripcion": "Destornillador con punta magnética y mango antideslizante, tamaño mediano.",
    "precio": 7.49
}

###
PUT {{apiProductos}}/2
Content-Type: application/json

{
    "id":2,
    "nombre": "Destornillador Phillips",
    "descripcion": "Destornillador con punta magnética y mango antideslizante, tamaño mediano.",
    "precio": 7.80

}

###
DELETE {{apiProductos}}/2

###
POST {{apiProductos}}/imagenes/1

###
DELETE  {{apiProductos}}/imagenes/1